import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { checkAddress, describeAddress, keccak256, parsePaymentUri } from "./address.ts";

// Real addresses generated by the bundled monero-ts WebAssembly engine (throwaway keys, no funds).
const REAL = {
  "mainnet": {
    "primary": "482xF4w1eyy6X81FNAe72vb41iNg3mBwE9Fu5dnabZhDdWVSdkwyZbeUrusNj9DKSHbqxuRxi3LPWYjCM74vqfLMTEQ3UcY",
    "sub": "87QxU3cq1xMQZmKWcSndo3PXzkde5KNYK5iT2qhmX7GUjo5tH1WSVaWeWPGU71LcaZ4BvDYKph8N39TFVMmQpDGjHCcjnJ8",
    "integrated": "4HjdFskWGFV6X81FNAe72vb41iNg3mBwE9Fu5dnabZhDdWVSdkwyZbeUrusNj9DKSHbqxuRxi3LPWYjCM74vqfLMfupTcYbWeJr3iRqNGP"
  },
  "testnet": {
    "primary": "9ttGKLeTqVxHsJ3hrCoktva5m4zSVTGgJDadAgQnXrFxQNkJGcFhuLoTACJ5Z27NnJ1iPLLXqX7NzjXNknK1PvZUNLPNR6v",
    "sub": "BZPGdSKUpgXiSqGG5ofGAJ7RJFFYJvMYseg4hrdM6sHVPSVWE8et3uW6PkbDz94qxJgDQ3Nnm6QubKasjHDeTAwiGHiHXuj",
    "integrated": "A4awL9TxSmUHsJ3hrCoktva5m4zSVTGgJDadAgQnXrFxQNkJGcFhuLoTACJ5Z27NnJ1iPLLXqX7NzjXNknK1PvZUYifY1qPJVoc3pKXrh4"
  },
  "stagenet": {
    "primary": "5AghcA3tZh37sfoUzfownQPY1pJDqxf4LJ2iNkVBxxhHQ1thFNGC1iePU5JcbJcP1bjPhAhP6QXz8L8jNEkjNrEC3aML6hu",
    "sub": "73PjjCrhLgpKn5huJuQGb2iZQiNwsWyMb3s3GmMJWgh9iWiBtd8d4EeGBPF4JUYuACEnP2QuQbQ6mRyAwzf6i12SBJTjiE7",
    "integrated": "5LPNcxsPAxZ7sfoUzfownQPY1pJDqxf4LJ2iNkVBxxhHQ1thFNGC1iePU5JcbJcP1bjPhAhP6QXz8L8jNEkjNrEC4nZCh2dvx8E3md7eTL"
  }
} as const;
const hex = (bytes: Uint8Array) => Buffer.from(bytes).toString("hex");

describe("offline address checks", () => {
  it("implements original Keccak-256, not SHA3", () => {
    assert.equal(hex(keccak256(new Uint8Array())), "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470");
    assert.equal(hex(keccak256(new TextEncoder().encode("abc"))), "4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45");
    assert.equal(hex(keccak256(new Uint8Array(300).map((_, i) => i & 255))), "a679e749a6af300c36e7ff2255d220864eab27b382f9cfdc5aa4d13563ba36ff");
  });
  for (const [network, values] of Object.entries(REAL)) {
    it(`recognises ${network} addresses and rejects single-character typos`, () => {
      const kinds = { primary: "standard", sub: "subaddress", integrated: "integrated" } as const;
      for (const [key, address] of Object.entries(values)) {
        assert.deepEqual(checkAddress(address), { valid: true, network, kind: kinds[key as keyof typeof kinds] });
        const replacement = address[20] === "A" ? "B" : "A";
        assert.equal(checkAddress(address.slice(0, 20) + replacement + address.slice(21)).valid, false);
      }
    });
  }
  it("explains network mismatches and malformed input", () => {
    assert.equal(describeAddress(REAL.mainnet.primary, "stagenet").tone, "error");
    assert.equal(describeAddress(REAL.stagenet.sub, "stagenet").tone, "valid");
    assert.deepEqual(checkAddress("4abc"), { valid: false, reason: "length" });
    assert.deepEqual(checkAddress("0".repeat(95)), { valid: false, reason: "characters" });
    assert.deepEqual(checkAddress(""), { valid: false, reason: "empty" });
  });
});
describe("payment links", () => {
  it("parses wallet2 and form-encoded links", () => {
    assert.deepEqual(parsePaymentUri(`monero:${REAL.stagenet.primary}?tx_amount=1.5&tx_description=Coffee%20%26+cake&recipient_name=Bob`),
      { address: REAL.stagenet.primary, amount: "1.5", description: "Coffee & cake", recipientName: "Bob" });
    assert.equal(parsePaymentUri(REAL.stagenet.primary), null);
    assert.ok("error" in (parsePaymentUri("monero:notanaddress") as object));
    assert.ok("error" in (parsePaymentUri(`monero:${REAL.stagenet.primary}?tx_amount=1e5`) as object));
    assert.ok("error" in (parsePaymentUri(`monero:${REAL.stagenet.primary}?tx_payment_id=${"a".repeat(64)}`) as object));
  });
});
